### ISSUE TITLE
Incorect neovim-qt formula!

### ISSUE THREAD

**Issue by khalidchawtany** [gwerbin/homebrew-tap#2]
The issue below results from the fact that, on Mac OS X a `build/bin/nvim-qt` executable is not created. Instead an application bundle is created named `build/bin/nvim-qt.app`.

```
brew install neovim-qt
==> Installing neovim-qt from gwerbin/tap
==> Downloading https://github.com/equalsraf/neovim-qt/archive/v0.2.2.tar.gz
Already downloaded: /Volumes/Home/Library/Caches/Homebrew/neovim-qt-0.2.2.tar.gz
==> Building Neovim-Qt
==> cmake ..
==> make
Error: No such file or directory - bin/nvim-qt
```

**Comment by gwerbin** [comment]
Was this a new change for version 0.2.2?

**Comment by khalidchawtany** [comment]
From merging [this](https://github.com/equalsraf/neovim-qt/pull/168), an application bundle is created instead of an nvim-qt executable. A week after this, 0.2.2 was released.

**Comment by gwerbin** [comment]
Thanks, it wasn't in the release notes from what I saw. In that case this should be migrated to a Cask, not a Formula.

**Comment by orip** [comment]
While we're waiting for neovim-qt to release binary Mac builds suitable for a cask, we should update the formula so 'brew install neovim-qt' actually works.

**Comment by gwerbin** [comment]
@orip thanks for this, sorry I had overlooked it for so long.
