### ISSUE TITLE
Invalid cask

### ISSUE THREAD

**Issue by Jo0p** [gwerbin/homebrew-tap#8]
➜  ~ brew install --cask firefox
==> Tapping homebrew/cask
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask'...
remote: Enumerating objects: 42, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 562580 (delta 18), reused 35 (delta 13), pack-reused 562538
Receiving objects: 100% (562580/562580), 249.83 MiB | 7.94 MiB/s, done.
Resolving deltas: 100% (397382/397382), done.
Error: Invalid cask: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/emacs.rb
Cask ''/Applications/Emacs.app/Contents/Resources/man/man1/ebrowse.1.gz' is not a valid man page name' definition is invalid.
Error: Cannot tap homebrew/cask: invalid syntax in tap!

**Comment by Jo0p** [comment]
> ➜ ~ brew install --cask firefox
> ==> Tapping homebrew/cask
> Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask'...
> remote: Enumerating objects: 42, done.
> remote: Counting objects: 100% (42/42), done.
> remote: Compressing objects: 100% (28/28), done.
> remote: Total 562580 (delta 18), reused 35 (delta 13), pack-reused 562538
> Receiving objects: 100% (562580/562580), 249.83 MiB | 7.94 MiB/s, done.
> Resolving deltas: 100% (397382/397382), done.
> Error: Invalid cask: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/emacs.rb
> Cask ''/Applications/Emacs.app/Contents/Resources/man/man1/ebrowse.1.gz' is not a valid man page name' definition is invalid.
> Error: Cannot tap homebrew/cask: invalid syntax in tap!

The issue has been solved by reinstalling homebrew.

**Comment by gwerbin** [comment]
DId you mean to post this on https://github.com/homebrew/homebrew-core ?
